version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3307:3306'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      #- MARIADB_ROOT_PASSWORD=H4DdGD6dqb6BBDNSsvqsdjqd,m
volumes:
  mariadb_data:
    driver: local
