version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3307:3306'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mariadb_data:
    driver: local
